### Prepare Raw Weather Data

This notebook combines all raw NOAA weather observation files into a single dataset, performs basic data preparation, and exports the processed data in **CSV** and **Apache Parquet** formats for downstream processing and analysis.

In [8]:
# Import libraries
from pathlib import Path
import pandas as pd
import pyarrow as pa

### Read Raw Files

In [ ]:
# Read the CSV/Excel files into DataFrames
raw_path = Path(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data"
)

dfs = []

for file in raw_path.glob("*.csv.gz"):
    df = pd.read_csv(
        file, 
        header=None
    )
    dfs.append(df)

weather = pd.concat(
    dfs,
    ignore_index=True
)

### Rename Columns

In [12]:
weather.head()

             0         1     2    3    4    5  6   7
0  ASN00012038  20150101  TMAX  353  NaN  NaN  a NaN
1  ASN00012038  20150101  TMIN  163  NaN  NaN  a NaN
2  ASN00012038  20150101  PRCP    0  NaN  NaN  a NaN
3  ASN00012038  20150101  TAVG  272    H  NaN  S NaN
4  ASN00012043  20150101  PRCP    0  NaN  NaN  a NaN

In [14]:
weather.rename(
    columns={
        0:'station',
        1:'observation_date',
        2:'metric',
        3:'value',
        4:'measurement_flag',
        5:'quality_flag',
        6:'source_flag',
        7:'observation_time'
        },
        inplace=True
    )

In [15]:
weather

,station,observation_date,metric,value,measurement_flag,quality_flag,source_flag,observation_time
0,ASN00012038,20150101,TMAX,353,NaN,NaN,a,NaN
1,ASN00012038,20150101,TMIN,163,NaN,NaN,a,NaN
2,ASN00012038,20150101,PRCP,0,NaN,NaN,a,NaN
3,ASN00012038,20150101,TAVG,272,H,NaN,S,NaN
4,ASN00012043,20150101,PRCP,0,NaN,NaN,a,NaN
...,...,...,...,...,...,...,...,...
422199389,USC00049035,20260716,TMIN,272,NaN,NaN,H,800.0
422199390,USC00049035,20260716,TOBS,283,NaN,NaN,H,800.0
422199391,USC00049035,20260716,PRCP,0,NaN,NaN,H,800.0
422199392,USC00049035,20260716,SNOW,0,NaN,NaN,H,NaN
422199393,USC00049035,20260716,SNWD,0,NaN,NaN,H,800.0

### Save as CSV file

In [13]:
weather.to_csv(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data\weather.csv",
    index=False
)

### Save as a Parquet file

In [16]:
weather.to_parquet(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data\weather.parquet",
    index=False,
    engine='pyarrow', # Parquet supports multiple engines; pyarrow is the most commonly used
    compression='snappy' # Compresses the file while keeping it fast to read and write. Compression saves storage and speeds up processing
)

ArrowKeyError: A type extension with name pandas.period already defined

## CSV vs Apache Parquet Benchmark

### Objective

Compare the storage efficiency and read performance of CSV and Apache Parquet formats using the same weather dataset.

### Dataset

- Source: NOAA Daily Climate Data
- Number of records:
- Number of columns:

### File Size Comparison

Compare the storage size of:

- weather.csv
- weather.parquet

### Read Performance

Measure the time required to load each file into a pandas DataFrame.

- CSV read time
- Parquet read time

### Summary

Briefly summarize the observed differences between both formats.

> **Note:** Benchmark results depend on the hardware, storage device, operating system, and software versions. The measurements presented here are intended for illustrative purposes only.

csv zapisywało się 9 minut 11 sekund