### Prepare Raw Weather Data Using Pandas

This notebook combines all raw NOAA weather observation files into a single dataset, performs basic data preparation, and exports the processed data in **CSV** and **Apache Parquet** formats for downstream processing and analysis.

In [13]:
# Import libraries and define paths
from pathlib import Path
import pandas as pd

RAW_DATA_PATH = Path(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data"
)

CSV_EXPORT = RAW_DATA_PATH / "weather.csv"
PARQUET_EXPORT = RAW_DATA_PATH / "weather.parquet"

### Read Raw Files

In [ ]:
# Read and combine all compressed CSV files
dfs = []

for file in RAW_DATA_PATH.glob("*.csv.gz"):
    df = pd.read_csv(
        file, 
        header=None
    )
    dfs.append(df)

weather = pd.concat(
    dfs,
    ignore_index=True
)

### Rename Columns

In [3]:
weather.head()

             0         1     2    3    4    5  6   7
0  ASN00012038  20150101  TMAX  353  NaN  NaN  a NaN
1  ASN00012038  20150101  TMIN  163  NaN  NaN  a NaN
2  ASN00012038  20150101  PRCP    0  NaN  NaN  a NaN
3  ASN00012038  20150101  TAVG  272    H  NaN  S NaN
4  ASN00012043  20150101  PRCP    0  NaN  NaN  a NaN

In [ ]:
weather.rename(
    columns={
        0:'station',
        1:'observation_date',
        2:'metric',
        3:'value',
        4:'measurement_flag',
        5:'quality_flag',
        6:'source_flag',
        7:'observation_time'
        },
        inplace=True
    )

In [ ]:
weather.head()

,station,observation_date,metric,value,measurement_flag,quality_flag,source_flag,observation_time
0,ASN00012038,20150101,TMAX,353,NaN,NaN,a,NaN
1,ASN00012038,20150101,TMIN,163,NaN,NaN,a,NaN
2,ASN00012038,20150101,PRCP,0,NaN,NaN,a,NaN
3,ASN00012038,20150101,TAVG,272,H,NaN,S,NaN
4,ASN00012043,20150101,PRCP,0,NaN,NaN,a,NaN

### Save as CSV file

In [ ]:
weather.to_csv(
    CSV_EXPORT,
    index=False
)

### Save as a Parquet file

In [ ]:
weather.to_parquet(
    PARQUET_EXPORT,
    index=False,
    engine='pyarrow', # Parquet supports multiple engines; pyarrow is the most commonly used
    compression='snappy' # Compresses the file while keeping it fast to read and write. Compression saves storage and speeds up processing
)