### Prepare Raw Weather Data Using Polars

This notebook combines all raw NOAA weather observation files into a single dataset, performs basic data preparation, and exports the processed data in **CSV** and **Apache Parquet** formats for downstream processing and analysis.

In [7]:
# Import libraries and define paths
from pathlib import Path
import polars as pl
import glob

RAW_DATA_PATH = Path(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data"
)

CSV_EXPORT = RAW_DATA_PATH / "weather_polars.csv"
PARQUET_EXPORT = RAW_DATA_PATH / "weather_polars.parquet"

### Read Raw Files

In [ ]:
# Read and combine all compressed CSV files

In [15]:
weather = pl.read_csv(
    RAW_DATA_PATH / "*.csv.gz",
    has_header=False
)

weather

shape: (422_199_394, 8)
┌─────────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ column_1    ┆ column_2 ┆ column_3 ┆ column_4 ┆ column_5 ┆ column_6 ┆ column_7 ┆ column_8 │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ i64      ┆ str      ┆ i64      ┆ str      ┆ str      ┆ str      ┆ str      │
╞═════════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ ASN00012038 ┆ 20150101 ┆ TMAX     ┆ 353      ┆ null     ┆ null     ┆ a        ┆ null     │
│ ASN00012038 ┆ 20150101 ┆ TMIN     ┆ 163      ┆ null     ┆ null     ┆ a        ┆ null     │
│ ASN00012038 ┆ 20150101 ┆ PRCP     ┆ 0        ┆ null     ┆ null     ┆ a        ┆ null     │
│ ASN00012038 ┆ 20150101 ┆ TAVG     ┆ 272      ┆ H        ┆ null     ┆ S        ┆ null     │
│ ASN00012043 ┆ 20150101 ┆ PRCP     ┆ 0        ┆ null     ┆ null     ┆ a        ┆ null     │
│ …           ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        │
│ USC00049035 ┆ 20260716 ┆ TMIN     ┆ 272      ┆ null     ┆ null     ┆ H        ┆ 0800     │
│ USC00049035 ┆ 20260716 ┆ TOBS     ┆ 283      ┆ null     ┆ null     ┆ H        ┆ 0800     │
│ USC00049035 ┆ 20260716 ┆ PRCP     ┆ 0        ┆ null     ┆ null     ┆ H        ┆ 0800     │
│ USC00049035 ┆ 20260716 ┆ SNOW     ┆ 0        ┆ null     ┆ null     ┆ H        ┆ null     │
│ USC00049035 ┆ 20260716 ┆ SNWD     ┆ 0        ┆ null     ┆ null     ┆ H        ┆ 0800     │
└─────────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

### Rename Columns

In [16]:
weather.head()

shape: (5, 8)
┌─────────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ column_1    ┆ column_2 ┆ column_3 ┆ column_4 ┆ column_5 ┆ column_6 ┆ column_7 ┆ column_8 │
│ ---         ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ i64      ┆ str      ┆ i64      ┆ str      ┆ str      ┆ str      ┆ str      │
╞═════════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ ASN00012038 ┆ 20150101 ┆ TMAX     ┆ 353      ┆ null     ┆ null     ┆ a        ┆ null     │
│ ASN00012038 ┆ 20150101 ┆ TMIN     ┆ 163      ┆ null     ┆ null     ┆ a        ┆ null     │
│ ASN00012038 ┆ 20150101 ┆ PRCP     ┆ 0        ┆ null     ┆ null     ┆ a        ┆ null     │
│ ASN00012038 ┆ 20150101 ┆ TAVG     ┆ 272      ┆ H        ┆ null     ┆ S        ┆ null     │
│ ASN00012043 ┆ 20150101 ┆ PRCP     ┆ 0        ┆ null     ┆ null     ┆ a        ┆ null     │
└─────────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

In [20]:
weather = weather.rename({
    "column_1": "station",
    "column_2": "observation_date",
    "column_3": "metric",
    "column_4": "value",
    "column_5": "measurement_flag",
    "column_6": "quality_flag",
    "column_7": "source_flag",
    "column_8": "observation_time"
})

In [21]:
weather.head()

shape: (5, 8)
┌─────────────┬─────────────┬────────┬───────┬─────────────┬─────────────┬────────────┬────────────┐
│ station     ┆ observation ┆ metric ┆ value ┆ measurement ┆ quality_fla ┆ source_fla ┆ observatio │
│ ---         ┆ _date       ┆ ---    ┆ ---   ┆ _flag       ┆ g           ┆ g          ┆ n_time     │
│ str         ┆ ---         ┆ str    ┆ i64   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│             ┆ i64         ┆        ┆       ┆ str         ┆ str         ┆ str        ┆ str        │
╞═════════════╪═════════════╪════════╪═══════╪═════════════╪═════════════╪════════════╪════════════╡
│ ASN00012038 ┆ 20150101    ┆ TMAX   ┆ 353   ┆ null        ┆ null        ┆ a          ┆ null       │
│ ASN00012038 ┆ 20150101    ┆ TMIN   ┆ 163   ┆ null        ┆ null        ┆ a          ┆ null       │
│ ASN00012038 ┆ 20150101    ┆ PRCP   ┆ 0     ┆ null        ┆ null        ┆ a          ┆ null       │
│ ASN00012038 ┆ 20150101    ┆ TAVG   ┆ 272   ┆ H           ┆ null        ┆ S          ┆ null       │
│ ASN00012043 ┆ 20150101    ┆ PRCP   ┆ 0     ┆ null        ┆ null        ┆ a          ┆ null       │
└─────────────┴─────────────┴────────┴───────┴─────────────┴─────────────┴────────────┴────────────┘

### Save as CSV file

In [23]:
weather.write_csv(CSV_EXPORT)

### Save as a Parquet file

In [25]:
weather.write_parquet(
    PARQUET_EXPORT,
    compression='snappy'
    )