### Prepare Sample weather_sample Data

This notebook creates a 100 000-row sample from the raw NOAA weather_sample observation data, performs basic data preparation, and exports the sample as a CSV file for testing the Docker PostgreSQL loading process.

In [14]:
# Import libraries and define paths
from pathlib import Path
import pandas as pd

RAW_DATA_PATH = Path(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data"
)

CSV_EXPORT = RAW_DATA_PATH / "weather_sample.csv"

### Read 100 000 Sample Rows

In [15]:
# Read 100 000 sample rows
weather_sample = pd.read_csv(
    r"C:\Users\zychl\Desktop\Data Engineering\weather_data_processing\00_raw_data\2025.csv.gz", 
    header=None,
    nrows=100_000
)

### Rename Columns

In [16]:
weather_sample.head()

             0         1     2    3    4    5  6   7
0  ASN00009515  20250101  PRCP    0  NaN  NaN  a NaN
1  ASN00009518  20250101  TMAX  243  NaN  NaN  a NaN
2  ASN00009518  20250101  TMIN  177  NaN  NaN  a NaN
3  ASN00009518  20250101  PRCP    0  NaN  NaN  a NaN
4  ASN00009518  20250101  TAVG  210    H  NaN  2 NaN

In [17]:
weather_sample.rename(
    columns={
        0:'station',
        1:'observation_date',
        2:'metric',
        3:'value',
        4:'measurement_flag',
        5:'quality_flag',
        6:'source_flag',
        7:'observation_time'
        },
        inplace=True
    )

In [18]:
weather_sample.head()

,station,observation_date,metric,value,measurement_flag,quality_flag,source_flag,observation_time
0,ASN00009515,20250101,PRCP,0,NaN,NaN,a,NaN
1,ASN00009518,20250101,TMAX,243,NaN,NaN,a,NaN
2,ASN00009518,20250101,TMIN,177,NaN,NaN,a,NaN
3,ASN00009518,20250101,PRCP,0,NaN,NaN,a,NaN
4,ASN00009518,20250101,TAVG,210,H,NaN,2,NaN

### Save as CSV file

In [19]:
weather_sample.to_csv(
    CSV_EXPORT,
    index=False
)